//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int Id { get; set; }
        public bool Timer { get; set; }
        public Nullable<int> Minutes { get; set; }
        public bool Schedule { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public bool Garden { get; set; }
    }
}
