//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPlant
    {
        public int Id { get; set; }
        public int IdPlant { get; set; }
        public int IdUser { get; set; }
        public int IdSensor { get; set; }
        public int ReadingTime { get; set; }
        public bool Active { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual Sensor Sensor { get; set; }
        public virtual User User { get; set; }
    }
}
